-- DDL (Data Definition Language)
-- 1. CREATE
CREATE DATABASE LEARNING;

-- use Learning;
CREATE TABLE STUDENT (
	SID INT PRIMARY KEY,
	SNAME VARCHAR(255),
	GPA DECIMAL(3, 2),
	SIZEHS FLOAT,
	DOB DATE
);

CREATE TABLE APPLY (
	SID INT,
	CNAME VARCHAR(255),
	MAJOR VARCHAR(255),
	DECISION CHAR(1)
);

-- 2. DROP
-- drop table Student;
-- drop table Apply;
-- 3. ALTER
ALTER TABLE STUDENT
ALTER COLUMN SIZEHS TYPE INTEGER;

-- 4. TRUNCATE
TRUNCATE STUDENT;

SELECT
	*
FROM
	STUDENT;